server:
  port: 9000
spring:
  cloud:
    gateway:
      routes:
      - id: api1
        uri: http://localhost:5000
        predicates:
        - Path=/api1/**
      - id: api2
        uri: http://localhost:3001
        predicates:
        - Path=/api2/**
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
      
  
